### ISSUE TITLE
Problem launching My DocManager

### ISSUE THREAD

**Issue by rescommunes** [10gen-labs/mongo-connector#208]
Following the instructions for Writing Your Own DocManager i've created a package with the following structure. 

```
src/__init__.py
src/mongo_connector/__init__.py
src/mongo_connector/doc_managers/__init__.py
src/mongo_connector/doc_managers/whoosh_doc_manager.py
```

All the \_\_init\_\_ files are empty except `src/mongo_connector/doc_managers/__init__.py` which contains

```python
from pkgutil import extend_path
__path__ = extend_path(__path__, __name__)
```

`whoosh_doc_manager.py` contains `class DocManager(DocManagerBase)` and works fine when I load it up from a file called `whoosh_connector.py` inside my package.  `python whoosh_connector.py -d whoosh_doc_manager`. 

**whoosh_connector.py**

```python
import logging
from mongo_connector.connector import main

if __name__ == '__main__':
    logging.basicConfig(level=logging.DEBUG)
    main()
```

But, I would like to use the suggested method of loading my custom module. When run  `$ mongo-connector -d whoosh_doc_manager` my DocManager is not found.

```python
Traceback (most recent call last):
  File "/Users/abox/Documents/mongo-connector-whoosh/env-mac/bin/mongo-connector", line 11, in <module>
    sys.exit(main())
  File "/Users/abox/Documents/mongo-connector-whoosh/env-mac/lib/python2.6/site-packages/mongo_connector/util.py", line 85, in wrapped
    func(*args, **kwargs)
  File "/Users/abox/Documents/mongo-connector-whoosh/env-mac/lib/python2.6/site-packages/mongo_connector/connector.py", line 950, in main
    conf.parse_args()
  File "/Users/abox/Documents/mongo-connector-whoosh/env-mac/lib/python2.6/site-packages/mongo_connector/config.py", line 114, in parse_args
    option, dict((k, values.get(k)) for k in option.cli_names))
  File "/Users/abox/Documents/mongo-connector-whoosh/env-mac/lib/python2.6/site-packages/mongo_connector/connector.py", line 778, in apply_doc_managers
    module = import_dm_by_name(dm['docManager'])
  File "/Users/abox/Documents/mongo-connector-whoosh/env-mac/lib/python2.6/site-packages/mongo_connector/connector.py", line 768, in import_dm_by_name
    "Could not import %s." % full_name)
mongo_connector.errors.InvalidConfiguration: Could not import mongo_connector.doc_managers.whoosh_doc_manager.
```

I'm not sure what i'm doing wrong and honestly I don't get how `extend_path` is being used to make this work. 

Thanks for your attention
Noel

**Comment by lovett89** [comment]
@rescommunes 
Thanks for filing an issue! The docs were wrong; I just fixed them. The `extend_path` code should go into `mongo_connector/__init__.py`, not `mongo_connector/doc_managers/__init__.py`. Also, this new "mongo_connector" package needs to be installed, or at least on your PYTHONPATH to work.

Project structure:

    project/mongo_connector/__init__.py  <-- extend_path code goes in here
    project/mongo_connector/doc_managers/__init__.py
    project/mongo_connector/doc_managers/custom_doc_manager.py

Quick test to see that it works:

    cd project
    export PYTHONPATH=.
    # Should not raise InvalidConfiguration because of missing doc_manager
    mongo_connector -d custom_doc_manager

**Comment by rescommunes** [comment]
Thanks for the response. However, I'm still having issues.

I should add that I'm using python 2.7 in a virutalenv. 

I'm not sure if `mongo_connector ` is somthing different from `mongo-connector`. Anyways, I proceeded as follows: 

I moved the `extend_path` to `src/mongo_connector/__init__.py`. 

Then setup as suggested

```bash
SunRoom:mongo-connector-whoosh abox$ source env-mac/bin/activate
(env-mac)SunRoom:mongo-connector-whoosh abox$ cd src/
(env-mac)SunRoom:src abox$ export PYTHONPATH=.
(env-mac)SunRoom:src abox$ mongo-connector -d whoosh_doc_manager
```

And I get a different error message

```python
Traceback (most recent call last):
  File "/Users/abox/Documents/development/mongo-connector-whoosh/env-mac/bin/mongo-connector", line 7, in <module>
    from mongo_connector.connector import main
  File "/Users/abox/Documents/development/mongo-connector-whoosh/env-mac/lib/python2.7/site-packages/mongo_connector/connector.py", line 31, in <module>
    from mongo_connector.doc_managers import doc_manager_simulator as simulator
ImportError: cannot import name doc_manager_simulator

```

**Comment by lovett89** [comment]
`mongo-connector` is the name of the project directory in this repository, whereas `mongo_connector` is the name of the Python package. I'm not completely sure where the `src` directory is in your example; is it the directory that contains the `mongo_connector` directory? I'll give a more complete example with pretend absolute paths. I'll pretend that "src" is where you keep code for all your projects, and I'll assume that your current project is called "woosh-mongo". Your directory structure should look like this:


    /home/rescommunes/src/woosh-mongo/README.rst  <-- stuff at top-level of project
    /home/rescommunes/src/woosh-mongo/setup.py
    /home/rescommunes/src/woosh-mongo/mongo_connector/__init__.py  <-- magic
    /home/rescommunes/src/woosh-mongo/mongo_connector/doc_managers/__init__.py  <-- can be completely empty
    /home/rescommunes/src/woosh-mongo/mongo_connector/doc_managers/woosh_doc_manager.py  <-- your code

When this is laid out, we can do:

    source ~/env-mac/bin/activate
    cd /home/rescommunes/src/whoosh-mongo

Then, if you have a setup.py, you can do this:

    python setup.py install
    
But if you don't have one yet, this will also work:

    export PYTHONPATH=.
    mongo-connector -d whoosh_doc_manager

When you set `PYTHONPATH` to `.`, you have to stay in the same directory when you launch mongo-connector, or else it won't find your DocManager. You could also `export PYTHONPATH=$(pwd)` or something so you aren't restricted by this. To actually distribute your DocManager, I highly recommend writing a `setup.py`.

By the way, this idea comes from the [backports](https://bitbucket.org/brandon/backports/src/ab8941ee5550?at=default) package. Their [setup.py](https://bitbucket.org/brandon/backports/src/ab8941ee55509833e4876990331e0d193f8eb9bc/setup.py?at=default) also gives a good explanation for how to use `extend_path` to bring modules into a Python namespace.

**Comment by rescommunes** [comment]
The problem now seems to be that it's not seeing  `mongo-connectors`'s `doc_managers`. In the last comment i sent the import error was `ImportError: cannot import name doc_manager_simulator`. `doc_manager_simulator` is inside your package. (I shouldn't have rushed that reply).

It seems that the `extend_path` is replacing everything in `doc_managers` with mine. 

It seems that the it does not work... I could try creating a higher level package so that i would end up passing something like `-d namespace.my_doc_manger` and move the `extend_path` into `doc_managers/__init__.py`.

I'll let you know if that works. But, if you feel this is not the right approach please let me know and go back to working with the structure as you suggested.

**Comment by lovett89** [comment]
Can you try adding the `pkgutil.extend_path` snippet into the other `__init__.py` as well? So that both `woosh_mongo/mongo_connector/__init__.py` and `woosh_mongo/mongo_connector/doc_managers/__init__.py` have it?

**Comment by rescommunes** [comment]
Putting `pkgutil.extend_path` snippet into both `__init__.py` resulted in success!

**Comment by lovett89** [comment]
Great! I updated the documentation. Thanks for your patience.

**Comment by rescommunes** [comment]
if you interested i could send a pull request which uses zope.dottedname and wouldn't depend on this schema to load a docmanager. It would also be backwards compatible. 

Let me know

**Comment by behackett** [comment]
I think we want to limit dependencies to just what's absolutely necessary. This schema works well for backports and is the recommendation in pep-382.

**Comment by rescommunes** [comment]
You should probably link to that in the wiki page.

**Comment by lovett89** [comment]
Good idea. Done.

**Comment by hannelita** [comment]
Hi,
I think part of this discussion could go to the Wiki, in the **Writing Your Own Doc Manager**

Maybe something like this:
[..]
2. Put the following in your `mongo_connector/__init__.py` and `mongo_connector/doc_managers/__init__.py`:

        from pkgutil import extend_path
        __path__ = extend_path(__path__, __name__)

For testing in your local environment, assume that your main working directory that holds your projects is **'my_projects/'**. Your custom Doc Manager will be into **your_custom_doc_manager** directory. Following the above file structure, you should end up with:
        
        /home/your_user/my_projects/your_custom_doc_manager/README.md <-- top leve resources
        /home/your_user/my_projects/your_custom_doc_manager/setup.py <-- optional
        /home/your_user/my_projects/your_custom_doc_manager/mongo_connector/__init__.py
        /home/your_user/my_projects/your_custom_doc_manager/mongo_connector/doc_managers/__init__.py
        /home/your_user/src/woosh-mongo/mongo_connector/doc_managers/your_custom_doc_manager.py

Notice that `setup.py` is not required. You can still test your own doc manager without it, which is very convenient for development mode. To be able to test your work, after installing `mongo-connector`, simply run `export PYTHONPATH=.` inside `your_custom_doc_manager` working directory. This will (intuitively) point Python path to your current directory. The you can run `mongo-connector -t url_for_your_doc_manager:port -d your_custom_doc_manager`

[..]

**Comment by llvtt** [comment]
@hannelita I'm actually a little confused by the directory structure example... what's the `src` directory, and why is `your_custom_doc_manager.py` not within the directory structure of the `your_custom_doc_manager` project?

**Comment by hannelita** [comment]
@llvtt Ops, I'm sorry, I got some fragments from your discussion above and forgot to properly format the directory structure that I suggested to add into the wiki. Just fixed my previous comment, see if it clarifies.

**Comment by llvtt** [comment]
@hannelita 
I think you have some very good suggestions. I moved some stuff around from your comment and integrated it into the current wiki: https://github.com/10gen-labs/mongo-connector/wiki/Writing%20Your%20Own%20DocManager.

Noting that "setup.py" is not required for testing is very useful. What do you think of this page now? Let me know if you have any feedback/suggestions. Thank you very much for helping improve documentation!

**Comment by hannelita** [comment]
@llvtt Thanks a lot!!! :+1: I think it's way more clear now. Thanks!
